// buildkey writes the optional source file that embeds a local Gemini API key.
package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	bundleKeyName = "NANOBANANA_BUNDLE_KEY"
	geminiKeyName = "GEMINI_API_KEY"
)

var buildOutput io.Writer = os.Stdout

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "buildkey:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) < 1 {
		return errors.New("usage: buildkey <generated-go-path> [dotenv-path ...]")
	}

	key, source, found, err := findKey(args[1:])
	if err != nil {
		return err
	}
	if !found {
		fmt.Fprintln(buildOutput, "No API key bundled; set GEMINI_API_KEY at runtime.")
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(args[0]), 0o755); err != nil {
		return fmt.Errorf("create generated source directory: %w", err)
	}
	contents := "// Code generated by internal/buildkey; DO NOT EDIT.\n\npackage main\n\nfunc init() { bundledAPIKey = " + strconv.Quote(key) + " }\n"
	if err := os.WriteFile(args[0], []byte(contents), 0o600); err != nil {
		return fmt.Errorf("write generated API key source: %w", err)
	}
	if err := os.Chmod(args[0], 0o600); err != nil {
		return fmt.Errorf("set generated API key source permissions: %w", err)
	}
	fmt.Fprintf(buildOutput, "Bundled API key from %s\n", source)
	return nil
}

func findKey(paths []string) (key, source string, found bool, err error) {
	if value := os.Getenv(bundleKeyName); value != "" {
		return value, "environment " + bundleKeyName, true, nil
	}
	if value := os.Getenv(geminiKeyName); value != "" {
		return value, "environment " + geminiKeyName, true, nil
	}

	for _, path := range paths {
		data, readErr := os.ReadFile(path)
		if errors.Is(readErr, os.ErrNotExist) {
			continue
		}
		if readErr != nil {
			return "", "", false, fmt.Errorf("read dotenv file %s: %w", path, readErr)
		}
		values, parseErr := parseDotenv(string(data))
		if parseErr != nil {
			return "", "", false, fmt.Errorf("parse dotenv file %s: %w", path, parseErr)
		}
		if value := values[bundleKeyName]; value != "" {
			return value, path, true, nil
		}
		if value := values[geminiKeyName]; value != "" {
			return value, path, true, nil
		}
		return "", "", false, nil
	}
	return "", "", false, nil
}

// parseDotenv handles only assignment syntax. Values are never evaluated or
// expanded, so shell metacharacters such as $ and backticks remain literal.
func parseDotenv(input string) (map[string]string, error) {
	values := make(map[string]string)
	for lineNumber, line := range strings.Split(input, "\n") {
		line = strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "export") {
			rest := strings.TrimPrefix(line, "export")
			if len(rest) == 0 || (rest[0] != ' ' && rest[0] != '\t') {
				continue
			}
			line = strings.TrimSpace(rest)
		}

		name, rawValue, hasAssignment := strings.Cut(line, "=")
		name = strings.TrimSpace(name)
		if name != bundleKeyName && name != geminiKeyName {
			continue
		}
		if !hasAssignment {
			return nil, fmt.Errorf("line %d has a malformed %s assignment", lineNumber+1, name)
		}
		value, err := parseValue(rawValue)
		if err != nil {
			return nil, fmt.Errorf("line %d has a malformed %s assignment", lineNumber+1, name)
		}
		values[name] = value
	}
	return values, nil
}

func parseValue(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", nil
	}
	if raw[0] == '\'' || raw[0] == '"' {
		quote := raw[0]
		end := strings.IndexByte(raw[1:], quote)
		if end < 0 {
			return "", errors.New("unterminated quote")
		}
		end++
		trailing := strings.TrimSpace(raw[end+1:])
		if trailing != "" && !strings.HasPrefix(trailing, "#") {
			return "", errors.New("unexpected text after quote")
		}
		return raw[1:end], nil
	}
	if comment := strings.IndexByte(raw, '#'); comment >= 0 {
		raw = raw[:comment]
	}
	return strings.TrimSpace(raw), nil
}
